import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Makimates</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[url('/images/background.jpg')] bg-cover bg-[20%] md:items-end md:bg-[url('/images/background-desktop.jpg')] md:pr-44">
        <motion.div
          className=" text-5xl font-bold text-white"
          initial={{
            opacity: 0,
          }}
          animate={{
            opacity: 1,
          }}
        >
          <h1>Makimates</h1>
        </motion.div>
        <div className="mt-8 w-60 cursor-pointer bg-orange-500 p-2 text-center ">
          Login with Google
        </div>
        <div className="mt-4 w-60 cursor-pointer bg-gray-800 p-2 text-center">
          Login with Github
        </div>
        <Link
          href="/table/1"
          className="mt-4 w-60 bg-green-600 p-2 text-center"
        >
          Go to table 1
        </Link>
      </main>
    </>
  );
};

export default Home;
